# NOTE: Please do not edit this file, it was auto generated by jhconvert
#       See http://wiki.sugarlabs.org/go/Deployment_Team/jhconvert for details

Name: sugar-write-activity
Version: 69
Release: %mkrel 2
Summary: Word processor for Sugar
License: GPLv2+
Group: Graphical desktop/Other
Url: http://sugarlabs.org/

Source: http://download.sugarlabs.org/sources/sucrose/fructose/Write/Write-69.tar.bz2

Requires: abiword >= 2.8
Requires: python-abiword  
Requires: sugar-toolkit >= 0.88.0

BuildRequires: gettext  
BuildRequires: sugar-toolkit >= 0.88.0

BuildRoot: %{_tmppath}/%{name}-%{version}-%{release}-root-%(%{__id_u} -n)
BuildArch: noarch

%description
The Write activity provides a word processor for the Sugar interface.

%prep
%setup -q -n Write-69


%build

rm -f MANIFEST
python setup.py build

%install
rm -rf %{buildroot}
python setup.py install --prefix=%{buildroot}/%{_prefix}
find %{buildroot} -name '*.py.orig' -print0 | xargs -0 rm -f
%find_lang org.laptop.AbiWordActivity

%clean
rm -rf %{buildroot}

%files -f org.laptop.AbiWordActivity.lang
%defattr(-,root,root,-)
%{_datadir}/sugar/activities/*
%doc NEWS

